address_file = "../input/Address file.csv"
male_names_file = "../input/male_names.txt"
female_names_file = "../input/female_names.txt"
age_probability_relation_file = "../configuration/age_probability_relation.csv"
coverage_limit_file = "../input/coverage_limits.csv"
occ_file = "../input/occupation.txt"
occ_age_specific = ["Office Clerical-579","Attorney-5103","Judges-43","Office_Clerical-23630","Fireman/Policeman-71"]
occ_other = ["Retired-626516","Other-1975721","Unknown-3379182","Self Employed-664","Self_Employed-31714"]
vin_data_file = "/elastic_search_test/Unique_VIN_Data.csv"